### PR TITLE
Implemented conditional dynamic blocks for `google_access_context_manager_service_perimeter` `spec` and `status`

### LINKED ISSUE #1176: Permadiff in google_access_context_manager_service_perimeter
Hi,

I'm using [vpc-sc](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/72a11897a6af0f5ae371c58d8be97315cee4895f/modules/vpc-sc) module and I have permanent diff on my terraform state when I have bridge perimeters with only enforce(status) config or with only dry-run(spec) config .

Problem:
TF plan:
```tf
 # module.vpc-sc[0].google_access_context_manager_service_perimeter.bridge["landing_to_prod"] will be updated in-place
  ~ resource "google_access_context_manager_service_perimeter" "bridge" {
        id                        = "accessPolicies/XXXXXXXX/servicePerimeters/landing_to_prod"
        name                      = "accessPolicies/XXXXXXXX/servicePerimeters/landing_to_prod"
        # (4 unchanged attributes hidden)

      + spec {
          + resources = []
        }

        # (1 unchanged block hidden)
    }
```
Code:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/72a11897a6af0f5ae371c58d8be97315cee4895f/modules/vpc-sc/service-perimeters-bridge.tf#L30-L34

Possible code solution using dynamic blocks(like you have for regular perimeters):
```tf
  dynamic spec {
    for_each = each.value.spec_resources == null ? [] : each.value.spec_resources
    content {
      resources = each.value.spec_resources
    }
  }
  dynamic status {
    for_each = each.value.status_resources == null ? [] : each.value.status_resources 
    content {
      resources = each.value.status_resources
    }
  }
```

### PR DESCRIPTION
**Pull request by calexandre**
This PR implements conditional dynamic blocks for `google_access_context_manager_service_perimeter` `spec` and `status` blocks.

This way, ensures that `spec` and `status` blocks are only created when there is a `spec` or `status` respectively.

- closes #1176

### CODE REVIEW

**Review by juliocc — DISMISSED** [review]

**Comment by calexandre** [comment]
@juliocc I'm gonna need some help on this one...I've gone through the logs, and I think this is failing due to the current test plan which is trying to create a case where it omits both the `spec` and `status` blocks, which leads to the given errors.

What are your thoughts?

**Comment by juliocc** [comment]
So this PR is actually breaking tests. I'll leave it up to @ludoo since that's his stuff

**Comment by ludoo** [comment]
Hey Carlos, if you're not in too much of a hurry I can get to it this weekend. The change will probably impact the FAST security stage too, and I need to check it's not breaking stuff.

**Comment by calexandre** [comment]
> Hey Carlos, if you're not in too much of a hurry I can get to it this weekend. The change will probably impact the FAST security stage too, and I need to check it's not breaking stuff.

Sure thing. Let me know if you need anything else.

**Comment by ludoo** [comment]
Ok, so my reasoning is that you can only do that for `spec`, as the `status` block needs to be there even with no resources if  you set `use_explicit_dry_run_spec`. If this is ok with you, I can merge this.

**Comment by calexandre** [comment]
> Ok, so my reasoning is that you can only do that for `spec`, as the `status` block needs to be there even with no resources if you set `use_explicit_dry_run_spec`. If this is ok with you, I can merge this.

Sounds like a plan! Let's go with your suggestion 👍

**Review by ludoo — APPROVED** [review]
Thanks a lot for spotting this, and your patience while we checked the test errors! :)

**Pull request merged**
