### PR TITLE
Rename network load balancer modules

### PR DESCRIPTION
**Pull request by ludoo**
https://cloud.google.com/load-balancing/docs

### CODE REVIEW

**Comment by sruffilli** [comment]
There are still quite a few instances where "ILB" and "GLB" are referred to, mostly as descriptions or module names.
https://gist.github.com/sruffilli/fb617854cf1ef5a632f5312943fc3233

I guess we're ok with that - just making sure.

**Comment by ludoo** [comment]
Yep this is only the code part. READMEs will take a bit more care and can be done incrementally imho.

**Comment by sruffilli** [comment]
LGTM with some additional changes which can be postponed
https://gist.github.com/sruffilli/6f7d35c15cc907326e5ffbad637a09e0

**Review by sruffilli — APPROVED** [review]

**Review by juliocc — APPROVED** [review]
There are more instances of the old names but let's merge this PR and we update the rest as we go along

**Pull request merged**
