### PR TITLE
Fix "inconsistent conditional result types" error in `modules/vpc-sc`

### PR DESCRIPTION
**Pull request by joelvoss**
This PR fixes the issue described in issue #2675. I've also adapted one of the example based tests so that the incorrect behavior is checked in the future.

---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

### CODE REVIEW

**Comment by ludoo** [comment]
Thanks, I just wonder why you edit the ingress policy examples but the change to the factory code is for egress. :)

**Comment by joelvoss** [comment]
I thought it would be enough to just customize the ingress part of the example-based test. I can also extend the egress part as well if you like.

The adjustments in the code affect both ingress and egress.

**Comment by ludoo** [comment]
Thanks for clarifying. My preference would be to leave the current examples as is, and add an extra set of YAML/code rules to cover this case. It makes it easier to assess changes.

**Comment by joelvoss** [comment]
> Thanks for clarifying. My preference would be to leave the current examples as is, and add an extra set of YAML/code rules to cover this case. It makes it easier to assess changes.

No problem. I have reverted the changes to the current examples and added an extra set of YAML/code rules to cover this case instead.

**Review by ludoo — APPROVED** [review]
thanks a lot for this!

**Pull request merged**
