### PR TITLE
Add Automation Service Accounts Output

### PR DESCRIPTION
**Pull request by joshw123**
---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

### CODE REVIEW

**Comment by ludoo** [comment]
Thanks for this PR, can you address the linting errors?

**Comment by juliocc** [comment]
Hey @joshw123, thanks for this PR. I had a similar issue recently and decided to go with something like this in the FAST stage.

```hcl
output "projects" {
  description = "Created projects."
  value = {
    for k, v in module.projects.projects : k => {
      number     = v.number
      project_id = v.id
      automation_buckets = {
        for kk, vv in module.projects.automation_buckets :
        trimprefix(kk, "${k}/") => vv.name
        if startswith(kk, "${k}/")
      }
      automation_service_accounts = {
        for kk, vv in module.projects.automation_service_accounts :
        trimprefix(kk, "${k}/") => vv.email
        if startswith(kk, "${k}/")
      }
    }
  }
}
```

This links the actual automation service account to the project that created it, and it also gives you the buckets as well. 

What do you think?

**Comment by joshw123** [comment]
> Hey @joshw123, thanks for this PR. I had a similar issue recently and decided to go with something like this in the FAST stage.
> 
> ```hcl
> output "projects" {
>   description = "Created projects."
>   value = {
>     for k, v in module.projects.projects : k => {
>       number     = v.number
>       project_id = v.id
>       automation_buckets = {
>         for kk, vv in module.projects.automation_buckets :
>         trimprefix(kk, "${k}/") => vv.name
>         if startswith(kk, "${k}/")
>       }
>       automation_service_accounts = {
>         for kk, vv in module.projects.automation_service_accounts :
>         trimprefix(kk, "${k}/") => vv.email
>         if startswith(kk, "${k}/")
>       }
>     }
>   }
> }
> ```
> 
> This links the actual automation service account to the project that created it, and it also gives you the buckets as well.
> 
> What do you think?

Ah nice, Yeah this is a nicer way of doing it :) Thank You

**Comment by joshw123** [comment]
> Hey @joshw123, thanks for this PR. I had a similar issue recently and decided to go with something like this in the FAST stage.
> 
> ```hcl
> output "projects" {
>   description = "Created projects."
>   value = {
>     for k, v in module.projects.projects : k => {
>       number     = v.number
>       project_id = v.id
>       automation_buckets = {
>         for kk, vv in module.projects.automation_buckets :
>         trimprefix(kk, "${k}/") => vv.name
>         if startswith(kk, "${k}/")
>       }
>       automation_service_accounts = {
>         for kk, vv in module.projects.automation_service_accounts :
>         trimprefix(kk, "${k}/") => vv.email
>         if startswith(kk, "${k}/")
>       }
>     }
>   }
> }
> ```
> 
> This links the actual automation service account to the project that created it, and it also gives you the buckets as well.
> 
> What do you think?

Have you got a PR open for this already @juliocc Thank You!

**Comment by juliocc** [comment]
@joshw123 I don't have any open PR for it. Feel free to include it directly in yours.

**Comment by joshw123** [comment]
Ready to Approve when you are @juliocc @ludoo Thank You! :)

**Review by juliocc — APPROVED** [review]

**Comment by joshw123** [comment]
Thank You for taking a look at this @juliocc I completely forgot about it tbh 😄 ❤️

**Pull request merged**
