### PR TITLE
Bringing Ayman's changes into main repo

### PR DESCRIPTION
**Pull request by iht**
@lcaggio

### CODE REVIEW

**Comment by lcaggio** [comment]
Merged into da-tf-201 branch

**Comment by ludoo** [comment]
Can you please provide a rationale for the change, and if it comprises different things split it into separate PRs?

**Comment by ludoo** [comment]
Ah sorry, disregard, it's not merging to master :)

**Comment by iht** [comment]
Apologies for the uncleanliness of this PR. This is a branch for an internal training being delivered today, that just comments out some bits of one of the data blueprints. The fork's branch was behind master a bit, and there are some more commits that were brought with the PR. I did the merge commit to make sure that all the changes were compatible, as the destination branch already existed in this repo, and I was not sure I could merge everything. We will drop this branch one we are done with the training.

**Pull request merged**
