### PR TITLE
IAM interface refactor

### PR DESCRIPTION
**Pull request by ludoo**

### CODE REVIEW

**Review by juliocc — APPROVED** [review]

**Comment by gustavovalverde** [comment]
@ludoo Maybe this was expected, based on the `incompatible change` label. I'd like to keep up with the repo changes, but after re-applying  stage`0-bootstrap` I got this error and I'm not completely sure what's required to _migrate_ to the new approach. 

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.organization.google_organization_iam_member.bindings["roles/compute.orgFirewallPolicyAdmin-group:gcp-network-admins@organization.com"],
│ provider "provider[\"registry.terraform.io/hashicorp/google\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Error applying IAM policy for organization "***REDACTED***": Error setting IAM policy for organization "***REDACTED***": googleapi: Error 400: The role name must be in the form "roles/{role}", "organizations/{organization_id}/roles/{role}", or "projects/{project_id}/roles/{role}"., badRequest
│ 
│   with module.organization.google_organization_iam_binding.bindings["sa_resman_delegated_iam"],
│   on ../../../modules/organization/iam.tf line 51, in resource "google_organization_iam_binding" "bindings":
│   51: resource "google_organization_iam_binding" "bindings" {
```

When I retried, then I got:

```shell
│ Error: Error when reading or editing organizations/***REDACTED***/roles/organizationIamAdmin: googleapi: Error 403: You don't have permission to get the role at organizations/***REDACTED***/roles/organizationIamAdmin.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.roles.get",
│       "resource": "organizations/***REDACTED***/roles/organizationIamAdmin"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden
│ 
│   with module.organization.google_organization_iam_custom_role.roles["organizationIamAdmin"],
│   on ../../../modules/organization/iam.tf line 35, in resource "google_organization_iam_custom_role" "roles":
│   35: resource "google_organization_iam_custom_role" "roles" {
│ 
╵
╷
│ Error: Error when reading or editing organizations/***REDACTED***/roles/tenantNetworkAdmin: googleapi: Error 403: You don't have permission to get the role at organizations/***REDACTED***/roles/tenantNetworkAdmin.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.roles.get",
│       "resource": "organizations/***REDACTED***/roles/tenantNetworkAdmin"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden
│ 
│   with module.organization.google_organization_iam_custom_role.roles["tenantNetworkAdmin"],
│   on ../../../modules/organization/iam.tf line 35, in resource "google_organization_iam_custom_role" "roles":
│   35: resource "google_organization_iam_custom_role" "roles" {
│ 
╵
╷
│ Error: Error when reading or editing organizations/***REDACTED***/roles/serviceProjectNetworkAdmin: googleapi: Error 403: You don't have permission to get the role at organizations/***REDACTED***/roles/serviceProjectNetworkAdmin.
│ Details:
│ [
│   {
│     "@type": "type.googleapis.com/google.rpc.ErrorInfo",
│     "domain": "iam.googleapis.com",
│     "metadata": {
│       "permission": "iam.roles.get",
│       "resource": "organizations/***REDACTED***/roles/serviceProjectNetworkAdmin"
│     },
│     "reason": "IAM_PERMISSION_DENIED"
│   }
│ ]
│ , forbidden
│ 
│   with module.organization.google_organization_iam_custom_role.roles["serviceProjectNetworkAdmin"],
│   on ../../../modules/organization/iam.tf line 35, in resource "google_organization_iam_custom_role" "roles":
│   35: resource "google_organization_iam_custom_role" "roles" {
│ 
╵
```

**Comment by juliocc** [comment]
@gustavovalverde my guess is that the first error removed some permissions from the gcp-org-admins group. Can you double check gcp-network-admins has the [right permissions](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/fast/stages/0-bootstrap/organization-iam.tf#L52) at the org level? 

Also double check that you're a member of that group, but that's not something we change/touch from bootstrap.

**Comment by gustavovalverde** [comment]
Thank you @juliocc, I had to add some permissions that were removed, also had to remove my `0-bootstrap-providers.tf` to `init` the terraform configuration, and most errors were gone.

But this one still remains:
```
│ Error: Error applying IAM policy for organization "***REDACTED***": Error setting IAM policy for organization "***REDACTED***": googleapi: Error 400: The role name must be in the form "roles/{role}", "organizations/{organization_id}/roles/{role}", or "projects/{project_id}/roles/{role}"., badRequest
│ 
│   with module.organization.google_organization_iam_binding.bindings["sa_resman_delegated_iam"],
│   on ../../../modules/organization/iam.tf line 51, in resource "google_organization_iam_binding" "bindings":
│   51: resource "google_organization_iam_binding" "bindings" {
```

**Comment by gustavovalverde** [comment]
Fixed with:
- https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1621

**Pull request merged**
