### PR TITLE
Add bug fix in bucket local variable

### PR DESCRIPTION
**Pull request by luigi-bitonti**
As you suggested, I made the change only to the local variable.
With this change, "bucket" variable will have the value of "var.bucket_name" only if the bucket has to be created.
Otherwise, it will have the name of the created bucket.
---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Comment by wiktorn** [comment]
Oh, now I see the bug :-) Thanks a lot.

Let me update this a bit

**Comment by wiktorn** [comment]
Can you pull changes from [here](https://github.com/wiktorn/cloud-foundation-fabric/tree/luigi_bug_fix_cf) ? This adds tests that verify that the bug is actually fixed and also covers cloud functions v1.

**Comment by luigi-bitonti** [comment]
I did it. I don't know if it was the correct way to merge your change, but trying to merge all the branch a I saw that there are a lots file changed because your branch is is 81 commits behind GoogleCloudPlatform:master.
So I basically copied and pasted only the file changed on your last commit.

**Review by wiktorn — APPROVED** [review]

**Comment by wiktorn** [comment]
Thank you, I thought that I based that on your branch, but maybe I missed something. `git cherry-pick` should also work in this case.

**Pull request merged**
