### PR TITLE
feat: network user for dataflow service agent

### PR DESCRIPTION
**Pull request by ericyz**
Add the IAM permission to support dataflow workers running on shared VPC host network

### CODE REVIEW

**Comment by ericyz** [comment]
Please help to review

**Comment by wiktorn** [comment]
Thank you Eric for this. I think we are still missing few other resources on the list here:
* [Dataproc](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/network#create_a_cluster_that_uses_a_network_in_another_project)
* [Cloud Composer](https://cloud.google.com/composer/docs/how-to/managing/configuring-shared-vpc#edit_permissions_for_the_composer_agent_service_account)
* [Serverless VPC access](https://cloud.google.com/functions/docs/networking/shared-vpc-service-projects#grant-permissions) (for Cloud Run and Functions)
* [Datafusion](https://cloud.google.com/data-fusion/docs/how-to/create-private-ip#shared-vpc-network_1)
* [Datastream](https://cloud.google.com/datastream/docs/create-a-private-connectivity-configuration)

And I might still miss some of them.

**Comment by juliocc** [comment]
The right way to approach this would be to expose `shared_vpc_service_config.service_identity_iam` as a field in the project factory yaml.

Please see [this comment](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1518#issuecomment-1649812806)

**Comment by wiktorn** [comment]
Closing as implemented using a bit different approach in #1542

**Pull request closed without merging**
