### PR TITLE
Add support for shared VPC host project in the project-factory module.

### PR DESCRIPTION
**Pull request by miromichalicka**
---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

### CODE REVIEW

**Comment by ludoo** [comment]
Thank you, very clean PR :)

**Review by ludoo — COMMENTED** [review]
Can you add an example test in the module's README?

**Comment by miromichalicka** [comment]
Certainly, I'll work on tests later this week

**Comment by ludoo** [comment]
Superseded by #2300

**Pull request closed without merging**
