### PR TITLE
align, add fast_created_stage to project labels

### PR DESCRIPTION
**Pull request by drebes**

### CODE REVIEW

**Comment by ludoo** [comment]
Can we pause this until #1052 has been merged? That one has been in the works for 2 months and renames stages, I dread having to sort conflicts one more time :)

**Comment by drebes** [comment]
Sure, I'll leave this here and adapt/rebase once that comes in. (I was actually thinking about that one)

**Comment by juliocc** [comment]
@drebes you can merge this now (enjoy the conflicts)

**Comment by ludoo** [comment]
Roberto, I'm closing this as it will be much simpler to redo it on top of the renamed stages, than fix these conflicts.

**Pull request closed without merging**
