### PR TITLE
Removing project_id conditional from gke-cluster modules

### PR DESCRIPTION
**Pull request by mark1000**
Removing the project_id conditional and getting it directly from the variable.

### CODE REVIEW

**Comment by juliocc** [comment]
@ludoo we think the project_id in the `peering_config` parameter is unnecessary since it's always going to be the project of the cluster. 

Do you remember why we had it as an argument to the gke module?

**Comment by ludoo** [comment]
> @ludoo we think the project_id in the `peering_config` parameter is unnecessary since it's always going to be the project of the cluster.
> 
> Do you remember why we had it as an argument to the gke module?

If you are using Shared VPC it's the host project id AFAIK.

**Comment by juliocc** [comment]
> If you are using Shared VPC it's the host project id AFAIK.

Ah of course. I'll bring back the default and provide a more reasonable default.

**Comment by mark1000** [comment]
Ah, I didn't think about Shared VPC. Thanks!

**Comment by ludoo** [comment]
Closing this, feel free to reopen if anything needs changing.

**Pull request closed without merging**
