### PR TITLE
fix cloudbuild service account email

### PR DESCRIPTION
**Pull request by nathou**
The correct format for this service account is documented in https://cloud.google.com/build/docs/cloud-build-service-account

---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [ ] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

### CODE REVIEW

**Comment by wiktorn** [comment]
Thank you for reporting and fixing!

**Review by ludoo — COMMENTED** [review]
The cloud build service account only exists for legacy projects.

https://cloud.google.com/build/docs/cloud-build-service-account-updates

Can you point to the documentation that explains your change?

**Comment by ludoo** [comment]
@wiktorn are you sure this is ok?

**Comment by juliocc** [comment]
This is correct. Cloud Build has two service agents according to the [docs](https://cloud.google.com/iam/docs/service-agents):
image

Merging this, but it will be deprecated by my service agents PR ;)

**Comment by nathou** [comment]
Yes, I know this is a legacy service agent, but there are still existing projects using it. Thanks!

**Comment by ludoo** [comment]
> This is correct. Cloud Build has two service agents
> Merging this, but it will be deprecated by my service agents PR ;)

ok, perfect, I was going by the "we don't have a cb service agent anymore", which is true but only for new projects using default org policies

**Pull request merged**
