### PR TITLE
Allow for the service account email to be provided for a Pub/Sub BigQuery subscription

### PR DESCRIPTION
**Pull request by wintermi**
Allow for the service account email to be provided for a Pub/Sub BigQuery subscription.

PR that will allow you to define and pass-through the `service_account_email` attribute to the `bigquery_config`.

### CODE REVIEW

**Comment by wintermi** [comment]
Added an example in the README as requested.

**Comment by wintermi** [comment]
Committed a fix for the liniting / test failures

**Comment by wintermi** [comment]
Hopefully that should resolve the testing failures.

**Comment by ludoo** [comment]
This is still failing, please check our contributing guide on how to write tests. Closing this PR, will reopen with fixed code. Thanks for pushing this forward.

**Pull request closed without merging**
