### PR TITLE
Full examples for CMEK examples

### PR DESCRIPTION
**Pull request by wiktorn**
Fix E2E tests by ensuring that necessary resources already exists.

For CMEK examples - make them fully verbose and end-to-end.

For some, still explicit `depends_on` is required:
* cloud functions require additional grants to actually work with default service account, I'm considering moving this grant to `setup_module`

This is alternate fix to the one proposed in #2524.

---
**Checklist**

I applicable, I acknowledge that I have:
- [ ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ ] Ran `terraform fmt` on all modified files
- [ ] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

### CODE REVIEW

**Comment by wiktorn** [comment]
@juliocc Can you take a look at `modules/alloydb` here before I move forward with all other modules?

**Comment by wiktorn** [comment]
[E2E run](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/10652525356)

**Comment by juliocc** [comment]
> @juliocc Can you take a look at `modules/alloydb` here before I move forward with all other modules?

This looks much better.

**Comment by wiktorn** [comment]
I think this is as good as it gets. I split changes into two commits - one adding dependencies in outputs in modules, and the other fixing the tests themselves.

Ready for thorough review

**Review by juliocc — APPROVED** [review]
<3

**Pull request merged**
