### PR TITLE
Avoid unnecessary terraform plans for closed (unmerged) PRs

### PR DESCRIPTION
**Pull request by pbrumblay**
This change avoids unnecessary terraform plan operations.
---
When closing a PR without merging, the github workflow still kicks off and runs a terraform plan. This is a minor issue, but it surprised me. In this PR I've added a conditional check to avoid running unnecessary plans when a PR is discarded.

**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Review by ludoo — APPROVED** [review]
This is nice, thanks for addressing this!

Unfortunately, to work around Windows inabilty to support symlinks we've had to copy these templates in stages 0 and 1. Can you make sure the changes is applied there too?

**Comment by juliocc** [comment]
@ludoo does it make sense to try to replicate the same functionality in the gitlab workflow?

**Comment by ludoo** [comment]
> @lodoo - I've updated the other three files in stages 0 and 1 for this PR.

Thanks!!! We will log an issue to trakc this for gitlab too, as Julio suggests. I'll put this on automerge so it should go in as soon as all tests pass.

**Comment by ludoo** [comment]
Checks seem to be stuck for some reason...

**Pull request merged**
