### PR TITLE
Reintroduce docker image path output in AR module

### LINKED ISSUE #2432: #2396 broke the autopilot GKE pattern blueprint
#2396 breaks other terraform modules in Cloud Foundation Fabric, such as the blueprints/gke/patterns/autopilot-cluster which expects the registry to have image_path. This field was deleted in this PR.

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/3151b02edab9da6df606a19b5d77b40684a1c065/blueprints/gke/patterns/autopilot-cluster/outputs.tf#L28

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2396/files#diff-b40a1f2d7f7c111740c753eeca7968ba7bdb4539d40c111e5e57124662058094

_Originally posted by @shakeel in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/2396#issuecomment-2237232591_

### PR DESCRIPTION
**Pull request by ludoo**
Fixes #2432

### CODE REVIEW

**Review by juliocc — APPROVED** [review]
Thanks for cleaning up after me :)

**Comment by shakeel** [comment]
What happens to all of the users who still are relying on the old attribute image_path, wont it break countless others users? Shouldn't we publish guidance to users that image_path is now renamed to docker_image_path? Are there plans to update the broken usages at least in this git repo, such as autopilot cluster?

**Comment by shakeel** [comment]
Thanks for fixing it

**Comment by shakeel** [comment]
When we change attribute names for a core resource, there might be external users who still are dependent upon image_path instead of docker_image_path. Shouldn't this change be highlighted in breaking changes document somewhere?

**Comment by ludoo** [comment]
@shakeel we usually mark incompatible changes so they are flagged once we generate the changelog. I just did it, and will refresh the changelog shortly, thanks for flagging this. :)

**Pull request merged**
