### PR TITLE
update variables files for gke nodepool taints

### PR DESCRIPTION
**Pull request by jackspyder**
Hello, 

A small fix to the gke blueprint, and the fast gke module to allow passing of taint objects down through the modules.

### CODE REVIEW

**Comment by juliocc** [comment]
Thanks for the fix!

You have to run the [tfdoc script](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#quick-developer-workflow) to update the README file.

**Review by ludoo — APPROVED** [review]
Thanks for spotting this!

**Review by juliocc — APPROVED** [review]

**Comment by jackspyder** [comment]
Just noticed the readme issue, getting setup and will add my commit with the changes shortly.

**Comment by jackspyder** [comment]
@ludoo @juliocc docs fixed, sorry i missed them!

**Comment by ludoo** [comment]
You should see a merge button, just go a ahead and merge. :)

**Comment by jackspyder** [comment]
> You should see a merge button, just go a ahead and merge. :)



> You should see a merge button, just go a ahead and merge. :)

No merge button sorry, unless im being extremely dense.

**Comment by ludoo** [comment]
ach, my fault... let me merge, sorry for that and thanks for the PR

**Pull request merged**
