### PR TITLE
Add path_template_match and path_template_rewrite support to net-lb-app-ext 

### PR DESCRIPTION
**Pull request by rosmo**
Required for React apps for example: https://github.com/rosmo/react-app-cloud-function-gcs-bucket

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Comment by wiktorn** [comment]
Is this also supported for:
* modules/net-lb-app-ext-regional
* modules/net-lb-app-int-cross-region
* modules/net-lb-app-int
?

Would be great to keep those in sync.

**Comment by rosmo** [comment]
Let me have a look, you might be right. It's an Envoy feature, so everything GFE3 based should be working...

**Comment by rosmo** [comment]
There, I added the rest of them.

**Comment by wiktorn** [comment]
> Ah, looks like google_compute_region_url_map hasn't been updated with these vars, will revert those.

I'm not sure I follow that. I see both `path_template_match` in `path_template_rewrite` in the resource.

**Comment by ludoo** [comment]
> > Ah, looks like google_compute_region_url_map hasn't been updated with these vars, will revert those.
> 
> I'm not sure I follow that. I see both `path_template_match` in `path_template_rewrite` in the resource.

What's missing to merge this?

**Review by ludoo — APPROVED** [review]

**Comment by wiktorn** [comment]
I just added support for ILBs

**Pull request merged**
