### PR TITLE
Allow customizable prefix in net-vpc module PSA configs

### LINKED ISSUE #2529: Cannot Control Private Service Access Range Name within net-vpc module
Since version 31.0.0, the way psa is configured within the net-vpc module was changed. It now allows for multiple psa configurations for different service producers. However, introducing this update changed how the the PSA IP ranges are named. It appends the service producer to the range. 

```
# module.spoke-vpcs["fat"].google_compute_global_address.psa_ranges["servicenetworking-googleapis-com-psa"] must be replaced
  # (moved from module.spoke-vpcs["fat"].google_compute_global_address.psa_ranges["psa"])
-/+ resource "google_compute_global_address" "psa_ranges" {
      ~ creation_timestamp = "2024-08-07T04:15:40.256-07:00" -> (known after apply)
      ~ effective_labels   = {} -> (known after apply)
      ~ id                 = "..." -> (known after apply)
      ~ label_fingerprint  = "..." -> (known after apply)
      - labels             = {} -> null
      ~ name               = "psa" -> "servicenetworking-googleapis-com-psa" # forces replacement
      ~ network            = "..."
      ~ self_link          = "..." -> (known after apply)
      ~ terraform_labels   = {} -> (known after apply)
        # (5 unchanged attributes hidden)
    }
```

As a PSA range cannot be renamed, it must be replaced. There is not easy way (without resource migrations) to use the latest module if you have existing PSA ranges in use. 

A PSA range can be assigned to multiple service producers. Therefore the name of the range shouldn't be based on the producer. In the image below we can see the range james-test is assigned to two different service producers. 

image

Desired outcome would be to decouple the range name from the service producer. Or to support some backwards compatibility to ensure ranges aren't re-created

### PR DESCRIPTION
**Pull request by ludoo**
Fixes #2529

### CODE REVIEW

**Review by juliocc — APPROVED** [review]
lgtm!

**Comment by intotecho** [comment]
Really appreciate this fix as it saved having to delete and rebuild network elements in use.
However,  my plan is still trying to replace a psa_connection[0] with .psa_connection["servicenetworking.googleapis.com"] .


config 
```hcl
module "host_network" {
  source = "../cloud-foundation-fabric/modules/net-vpc"
  project_id                      = var.network_project_id
  auto_create_subnetworks         = false
  name                            = var.network_name
  delete_default_routes_on_create = true
  description                     = var.description
  shared_vpc_host                 = var.shared_vpc
  subnets                         = var.subnets
  subnets_proxy_only              = var.subnets_proxy_only
  shared_vpc_service_projects     = var.service_project_ids
  #subnet_iam_additive             = var.subnet_iam_permissions
  psa_configs = [{
    ranges = { range-a = "10.200.0.0/16" }
    range_prefix = ""
  }]
}

```
```hcl
module....host_network.google_service_networking_connection.psa_connection[0] will be destroyed
  # (because resource does not use count)
  - resource "google_service_networking_connection" "psa_connection" {
      - id                      = "projects%PROJECT%2Fglobal%2Fnetworks%2Fgeo-nw-uat:servicenetworking.googleapis.com" -> null
      - network                 = "projects/PROJECT/global/networks/geo-nw-uat" -> null
      - peering                 = "servicenetworking-googleapis-com" -> null
      - reserved_peering_ranges = [
          - "range-a",
        ] -> null
      - service                 = "servicenetworking.googleapis.com" -> null
    }
```

The apply fails because it is in use with error:
```
Unable to remove Service Networking Connection, err: Error waiting for Delete Service Networking Connection: Error code 9, message: Failed to delete connection; Producer services (e.g. CloudSQL, Cloud Memstore, etc.) are still using this connection.
```
I am not sure how to proceed?

**Comment by juliocc** [comment]
Can you share the full plan? I think that one can be fixed with a moved block.

**Comment by intotecho** [comment]
I was able to resolve this with

```bash
terraform state mv module.my_network.google_service_networking_connection.psa_connection[0]   module.my_network.google_service_networking_connection.psa_connection[\"servicenetworking.googleapis.com\"] 
```

**Pull request merged**
