### PR TITLE
Add dependencies on IAM grants, make E2E tests depend on IAM grants

### PR DESCRIPTION
**Pull request by wiktorn**
Fix missing IAM dependencies.

---
**Checklist**

I applicable, I acknowledge that I have:
- [ ] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [ ] Ran `terraform fmt` on all modified files
- [ ] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [ ] Made sure all relevant tests pass

### CODE REVIEW

**Comment by wiktorn** [comment]
[E2E test run](https://github.com/GoogleCloudPlatform/fast-e2e/actions/runs/10648462602)

**Comment by juliocc** [comment]
@wiktorn I would really prefer if we avoid using `depends_on` on examples. Having a `depends_on` there is an artifact of the e2e architecture. This is not how you would add those bindings it if you use the project module. 

Same thing with these bindings:
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/ecb83e9c4b26a018472d21473153f8c437e7f2c8/tests/fixtures/kms-global-regional-keys.tf#L26-L32

These are not as bad since they're in a fixture but examples are intended to show idiomatic code. I'd argue that we should drop e2e from those examples if we have to introduce code to support it

**Comment by ludoo** [comment]
> @wiktorn I would really prefer if we avoid using `depends_on` on examples. Having a `depends_on` there is an artifact of the e2e architecture. This is not how you would add those bindings it if you use the project module.
> 
> Same thing with these bindings:
> 
> https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/ecb83e9c4b26a018472d21473153f8c437e7f2c8/tests/fixtures/kms-global-regional-keys.tf#L26-L32
> 
> These are not as bad since they're in a fixture but examples are intended to show idiomatic code. I'd argue that we should drop e2e from those examples if we have to introduce code to support it

100% agree, e2e needs to take second not first place in cases like these

**Comment by wiktorn** [comment]
Closing this to save your cycles. For PR prioritizing removal of `depends_on` see #2546

**Pull request closed without merging**
