### PR TITLE
Add confidential compute support to google_dataproc_cluster in the da…

### PR DESCRIPTION
**Pull request by steenblik**
Add confidential compute support to dataproc module. 

---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

### CODE REVIEW

**Comment by steenblik** [comment]
Awaiting provider release. See: https://github.com/GoogleCloudPlatform/magic-modules/pull/12397

**Review by ludoo — APPROVED** [review]
Thanks Jason!

**Comment by steenblik** [comment]
@ludoo - The updated 6.13.0 provider has finally been released. How should I proceed? I guess I should update the provider requirements across all modules but would like confirmation.

**Comment by ludoo** [comment]
> @ludoo - The updated 6.13.0 provider has finally been released. How should I proceed? I guess I should update the provider requirements across all modules but would like confirmation.

`find . -name versions.tf -exec cp default-versions.tf {} \;` :)

**Comment by steenblik** [comment]
> `find . -name versions.tf -exec cp default-versions.tf {} \;` :)

Brilliant. Thanks!

**Comment by steenblik** [comment]
@ludoo - I believe this one is ready. Do you want to have one more look?

**Comment by ludoo** [comment]
Go ahead and hit the green button :)

**Pull request merged**
