### PR TITLE
Separating GKE Standard and Autopilot Modules

### PR DESCRIPTION
**Pull request by avinashkumar1289**
This Pull request contains changes for separating GKE autopilot and Standard Modules. 
I have commented out changes in the autopilot module, so it becomes easy to find what blocks I have removed before merging.

### CODE REVIEW

**Comment by avinashkumar1289** [comment]
@ludoo @juliocc  I am facing a lot of error because of the naming convention of the module. There are a lot of reference for gke-cluster and since I have divided them to gke-autopilot-cluster and gke-standard-cluster, few of the checks are not passing ? 
Please advice

**Comment by juliocc** [comment]
> @ludoo @juliocc I am facing a lot of error because of the naming convention of the module. There are a lot of reference for gke-cluster and since I have divided them to gke-autopilot-cluster and gke-standard-cluster, few of the checks are not passing ? Please advice

Hey @avinashkumar1289, it's not a naming convention issue. You actually removing a module that is a dependency elsewhere in the repo. The tests are failing because they depend on that module. This is exactly what should happen.

The PR should update those other parts of the codebase and ensure all the references to the existing module are updated and work as expected. The failing tests should actually help you figure out what is broken by the changes you're introducing.

If you want we can show you how to go about fixing some of those failures.

**Review by ludoo — APPROVED** [review]
Super job thanks a lot for tackling this! Can you remove the commented code in the autpilot mode before merging?

**Comment by avinashkumar1289** [comment]
@ludoo Thanks .Pushed the changes !!

**Comment by ludoo** [comment]
It's good to go for me, let's wait this morning so Julio can also give it a look, then you should be able to merge (do you see the green "Squash and merge" button?)

**Comment by avinashkumar1289** [comment]
@ludoo Thanks !! Yes lets wait for @juliocc to confirm !! 
Yes I see the "Squash and Merge" option under "Merge Pull request".

**Review by juliocc — APPROVED** [review]

**Comment by intotecho** [comment]
Hi, What is the reason why var.monitoring_config was removed from the autopilot version? Is it not supported in GKE?

**Comment by intotecho** [comment]
Thanks, makes sense. Are all the components enabled, like SYSTEM_COMPONENTS, APISERVER, CONTROLLER_MANAGER, and SCHEDULER?

**Comment by juliocc** [comment]
These are the details: https://cloud.google.com/kubernetes-engine/docs/resources/autopilot-standard-feature-comparison#:~:text=Logging%20and%20monitoring

**Comment by intotecho** [comment]
Thanks for the link! The new modules are very clean and a good improvement.
Note that deleting the old module instead of deprecating it forces users to
upgrade to either autopilot or standard when they upgrade the cloud
foundation fabric version.

**Comment by intotecho** [comment]
I am having trouble getting the gke autopilot cluster into BALANCED mode. 

Although the provider says BALANCED is the default. The console is reporting something else. 

> Autoscaling profile | Optimize utilization



</body>
</html>

```
  cluster_autoscaling {

    autoscaling_profile = "BALANCED"
    dynamic "auto_provisioning_defaults" {
      for_each = var.service_account != null ? [""] : []
      content {
        service_account = var.service_account
      }
    }
  }
```
I tried adding     **autoscaling_profile = "BALANCED"** in modules/gke-cluster-autopilot/main.tf
But it didn't change the infrastructure. 

I am not sure if this is user error, an issue with the google beta provider version "4.60" or the way it is called.

**Comment by wiktorn** [comment]
@intotecho I can confirm your findings. As far as I can tell, there are two bugs lurking here:
1. Providing `autoscaling_profile` in `google_container_cluster` does not change anything. As this is not editable on the cluster, it should destroy cluster and create new one. Nothing happens, because there is `DiffSuppressFunc` [defined]( https://github.com/hashicorp/terraform-provider-google-beta/blob/main/google-beta/resource_container_cluster.go#L743) which for autopilot clusters ignores any changes to field. It needs to be `ForceNew` to force cluster recreation.
2. When cluster is created without providing `autoscaling_profile`, clusters are created as `OPTIMIZE_UTILIZATION` which is against [API documentation](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster.AutoscalingProfile)

So as temporary workaround, after modifying `gke-cluster-autopilot` module force cluster recreation and it should recreate with proper profile:
```
terraform plan -out tf.plan -replace 'module.cluster-1.google_container_cluster.cluster'
```
(your module address may differ)
```

**Comment by wiktorn** [comment]
@intotecho Sorry, my bad. For autopilot clusters you can't modify this value.

**Comment by intotecho** [comment]
Ok, thanks for looking into it.
Regards Chris

**Pull request merged**
