### PR TITLE
Update `modules/artifact-registry` with newly-released features.

### LINKED ISSUE #2377: Artifactory does not support generic
**Describe the bug**
When I'm looking into the variables description I don't see any support on the generic artifact registry: 

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/6c54ab69db72364ebf03e98486addf54ed4a3464/modules/artifact-registry/variables.tf#L56

### PR DESCRIPTION
**Pull request by juliocc**
* Fixes #2377
* Add support for new formats and remote repo types
* Variable changes for simplified interface

### CODE REVIEW

**Review by ludoo — APPROVED** [review]

**Comment by shakeel** [comment]
This PR breaks other terraform modules in Cloud Foundation Fabric, such as the blueprints/gke/patterns/autopilot-cluster which expects the register to have image_path. This field was deleted in this PR.

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/3151b02edab9da6df606a19b5d77b40684a1c065/blueprints/gke/patterns/autopilot-cluster/outputs.tf#L28

https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/2396/files#diff-b40a1f2d7f7c111740c753eeca7968ba7bdb4539d40c111e5e57124662058094

**Comment by ludoo** [comment]
Thanks for flagging this, it looks like that blueprint has no tests, which is weird and why it was broken by the change. We'll send a fix shortly.

**Comment by juliocc** [comment]
@ludoo the gke patterns folder has no tests. Assign this to me and I'll fix it next week when I come back

**Comment by ludoo** [comment]
No worries, I can do it later :)

**Comment by ludoo** [comment]
@juliocc I'm going to revert the change that removed the registry URL from the outputs, I use it a lot as it saves me having to a) look for it in the docs, b) build it every time I use the module. It's what is breaking the blueprint BTW. I'm sure you had a reason for removing it, but it escapes me ATM. :)

**Comment by ludoo** [comment]
It's the equivalent to this in the UI

image

**Pull request merged**
