### PR TITLE
Allow factory files to be empty

### PR DESCRIPTION
**Pull request by LucaPrete**
Allow net-vpc-firewall factory files to be empty.

---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Review by ludoo — COMMENTED** [review]
hmmmmmm :)

**Comment by ludoo** [comment]
@wiktorn @juliocc I don't see anything against doing this here, WDYT?

**Comment by wiktorn** [comment]
Works for those two cases:

configs/firewall/rules/rule1.yaml:
```
---
```
configs/firewall/rules/rule2.yaml:
```
---

ingress: {}
egress: null
```

**Comment by juliocc** [comment]
LGTM

**Review by ludoo — APPROVED** [review]

**Pull request merged**
