### PR TITLE
Fix/dlpagent

### PR DESCRIPTION
**Pull request by ddaluka**
When DLP API service is enabled for a project, we also need its service agent to be available for further IAM roles assignment. 

dlp.googleapis.com API supports the identity creation using gcloud beta services identity create --service dlp.googleapis.com

---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Review by wiktorn — CHANGES_REQUESTED** [review]
If you need to have DLP service agent force-created, add to [service-agents.yaml](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project/service-agents.yaml#L170):
```
jit: true
```

For DLP

**Comment by ddaluka** [comment]
> If you need to have DLP service agent force-created, add to [service-agents.yaml](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/modules/project/service-agents.yaml#L170):
> 
> ```
> jit: true
> ```
> 
> For DLP. Also, bare in mind, that services force-created may miss their role, in this case it will be `roles/dlp.serviceAgent`, so this is not a perfect solution.

Thanks, I have removed the explicit identity creation block and have set jit as true . I guess , we can assign the service agent role if required once agent is available.

**Comment by wiktorn** [comment]
> Thanks, I have removed the explicit identity creation block and have set jit as true . I guess , we can assign the service agent role if required once agent is available.

Yes, we have this documented [here](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/modules/project#service-identities-requiring-manual-iam-grants)

Can you add DLP there too? Thanks.

**Comment by wiktorn** [comment]
@ddaluka There was still one blueprint tests that were failing due to this change, will you be able to fix that, or shall I help you with that?

**Review by wiktorn — APPROVED** [review]

**Comment by ddaluka** [comment]
> @ddaluka There was still one blueprint tests that were failing due to this change, will you be able to fix that, or shall I help you with that?

Thanks. I have fixed the issue

**Comment by wiktorn** [comment]
Thank you for fixing those :heart:

**Pull request merged**
