### PR TITLE
Project factory support for Serverless VPC Access connector permissions

### PR DESCRIPTION
**Pull request by ChrisF987**
Proposed project-factory update to support enabling access for Cloud Run, Cloud Functions and App Engine service agents to use Serverless VPC Access connectors that are deployed in a shared vpc host project. 

Relates to issue https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/1517

### CODE REVIEW

**Comment by juliocc** [comment]
@ChrisF987 what if you expose the whole `shared_vpc_service_config.service_identity_iam` as a field in the yaml? This would allow using any service identity and not just the serverless one.

**Comment by wiktorn** [comment]
Hi @ChrisF987,

I did a bit different implementation of this feature. One thing that I miss, is that you are also granting `roles/vpcaccess.user` for App Engine Standard robot. I would expect this to be mentioned [here](https://cloud.google.com/appengine/docs/standard/shared-vpc-host-project) but this doc is only mentioning that the role is needed for the user that is doing the deploy. Is this a bug in official docs?

**Comment by ChrisF987** [comment]
> Hi @ChrisF987,
> 
> I did a bit different implementation of this feature. One thing that I miss, is that you are also granting `roles/vpcaccess.user` for App Engine Standard robot. I would expect this to be mentioned [here](https://cloud.google.com/appengine/docs/standard/shared-vpc-host-project) but this doc is only mentioning that the role is needed for the user that is doing the deploy. Is this a bug in official docs?

Hi @wiktorn @juliocc , thanks for your comments, and for the implementation of service identity iam via your other PR. Re if `roles/vpcaccess.user` is necessary for App Engine Standard robot, I've reviewed the docs again and yea I just misread it whilst doing this PR.

**Comment by ChrisF987** [comment]
Implemented in https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/pull/1542

**Pull request closed without merging**
