### PR TITLE
Have Squid log to /dev/stdout to stream logs to Cloud Logging

### PR DESCRIPTION
**Pull request by kunzese**
This PR uses dark Docker voodoo to make the Squid container able to log to /dev/stdout, which then get streamed to Cloud Logging via the COS logging agent.

FYI: @gaspar-chilingarov

### CODE REVIEW

**Review by ludoo — APPROVED** [review]
almost calls for docker compose :)

**Comment by ludoo** [comment]
> > almost calls for docker compose :)
> 
> Good idea - i will adjust this PR.

you probably need to download docker-compose, which will then fail if there's no public access. :) interested in what you come up with, but this PR is totally fine as is if you want to merge!

**Comment by gaspar-chilingarov** [comment]
i have a strange feeling about starting container with **USER=${squid_user}** and then using `sudo` to get more privileges. Why not to run as a root then?

**Comment by gaspar-chilingarov** [comment]
LGTM :)

**Pull request merged**
