### PR TITLE
add AIRFLOW_VAR_ prefix to environment variables in data-platform blueprints

### PR DESCRIPTION
**Pull request by Tutuchan**
As discussed in #1649,  this PR adds the `AIRFLOW_VAR_` prefix to all environment variables in the [data-platform-foundations](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/data-solutions/data-platform-foundations) and [data-platform-minimal](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/tree/master/blueprints/data-solutions/data-platform-minimal) blueprints, to enable them being used as [Airflow Variables](https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/variables.html).

I also updated the example DAGs based on this change + took the liberty to remove unused imports.

---
**Checklist**

I applicable, I acknowledge that I have:
- [x] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [x] Ran `terraform fmt` on all modified files
- [x] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [x] Made sure all relevant tests pass

I add one test failing locally -- `tests/modules/cloud_function_v2/examples/iam.yaml` but I don't see how it's related to this change.

### CODE REVIEW

**Review by lcaggio — APPROVED** [review]
Thanks for the PR!

**Comment by Tutuchan** [comment]
Thanks for the approval @lcaggio, I'm waiting for an answer internally about the CLA, I'll get back to the PR when it has moved forward.

**Comment by Tutuchan** [comment]
Just FYI, CLA has been approved internally, we are waiting for the Google review which should take a few days.

**Comment by ludoo** [comment]
Fixes #1649

**Pull request merged**
