### PR TITLE
Add secure (network) tag bindings to compute-vm

### PR DESCRIPTION
**Pull request by LucaPrete**

### CODE REVIEW

**Comment by LucaPrete** [comment]
WIP. It seems the resource still has issues, plus testing using secure tags on instance templates as well. I'll get back asap with news

**Comment by juliocc** [comment]
It seems, yeah ;)

**Comment by ludoo** [comment]
I'm not clear on the difference between a binding, and a location binding. Luca I'll ping you

**Comment by LucaPrete** [comment]
To leave a note in the thread, as discussed legacy bindings don’t work with
network tags. You need to rely on a different API, so a different resource.
Waiting to merge this as a new bug  in the provider was recently fixed and
merged. Should be available publicly by the eow.

Il giorno lun 13 mar 2023 alle 16:22 Ludovico Magnocavallo <
***@***.***> ha scritto:

**Comment by LucaPrete** [comment]
Unfortunately, the provider seems to have a new bug. Waiting to get this solver.
Investigating more with @ghabian

**Comment by ludoo** [comment]
Luca, I'm closing this. Feel free to resubmit when ready.

**Pull request closed without merging**
