### PR TITLE
Normalize prefix handling in blueprints

### LINKED ISSUE #967: Prefix handling in blueprints
Similar to https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/954 , but for the blueprints folder. Mostly a perfectionistic ask, involves quite some boring work.

### PR DESCRIPTION
**Pull request by kunzese**
This PR normalizes the prefix handling in blueprints, similar to #964.

Fixes #967

### CODE REVIEW

**Comment by kunzese** [comment]
@skalolazka FYI

**Comment by juliocc** [comment]
Thanks @kunzese!

I'm not sure if we want the `default=null` for blueprints. @ludoo wdyt?

**Comment by ludoo** [comment]
> Thanks @kunzese!
> 
> I'm not sure if we want the `default=null` for blueprints. @ludoo wdyt?

true, blueprints could require the prefix to be passed in, so as not to default to existing project/bucket names

**Comment by kunzese** [comment]
> OMG, Sebastian, this is awesome! Thanks for taking your time! Nit: we did change "can not" to "cannot" in modules/ %)

But not in the `./CONTRIBUTING.md` where i copied it from :p but i adjusted it everywhere.

**Comment by kunzese** [comment]
@ludoo @juliocc what if we set a reasonable default value for prefix?

```
variable "prefix" {
  description = "Optional prefix used for resource names."
  type        = string
  default     = "blueprint" // demo or fast or example or whatever
  validation {
    condition     = var.prefix != ""
    error_message = "Prefix cannot be empty, please use null instead."
  }
}
```

This way everything has a prefix per default, the user does not have to supply one when they don't need, but we keep the possible to just not use any prefix if someone decides to do so.

**Comment by ludoo** [comment]
> @ludoo @juliocc what if we set a reasonable default value for prefix?
> 
> ```
> variable "prefix" {
>   description = "Optional prefix used for resource names."
>   type        = string
>   default     = "blueprint" // demo or fast or example or whatever
>   validation {
>     condition     = var.prefix != ""
>     error_message = "Prefix cannot be empty, please use null instead."
>   }
> }
> ```
> 
> This way everything has a prefix per default, the user does not have to supply one when they don't need, but we keep the possible to just not use any prefix if someone decides to do so.

The problem for blueprints (where there is no org-wide naming convention with a unique token, usually at the beginning of the name) is that setting a default prefix will originate clashes for each user after the first one that runs apply on project ids and GCS bucker names, which are unique across GCP.

For blueprints we should really not set a default for prefix, and ask users to set it in a tfvars file or pass it in via environment or arg.

**Comment by kunzese** [comment]
Reworked the prefix handling, so that it is now mandatory.

**Review by ludoo — APPROVED** [review]

**Pull request merged**
