### PR TITLE
feat: enable mtls on external application application load balancer

### PR DESCRIPTION
**Pull request by Tazminia**
This PR provides the following:

- Enable mTLS support on an external application load balancer by specifying a server tls policy.
- Add .python-version to git ignore for contributors with multiple python versions on their machines.

This is my first attempt contributing to the project, please let me know if I need to do further checks or changes. Also, I had tests failing but none of them seemed related to what I am changing.

---
**Checklist**

I applicable, I acknowledge that I have:
- [X] Read the [contributing guide](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md)
- [X] Ran `terraform fmt` on all modified files
- [X] Regenerated the relevant README.md files using [`tools/tfdoc.py`](https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/blob/master/CONTRIBUTING.md#fabric-tools)
- [X] Made sure all relevant tests pass

### CODE REVIEW

**Comment by juliocc** [comment]
I think the new flag should go under `var.https_proxy_config`. @ludoo wdyt?

**Comment by juliocc** [comment]
@Tazminia instead of a top level variable, can you add a field to `var.https_proxy_config`?

Thanks!

**Comment by Tazminia** [comment]
@juliocc of course. I will handle it and push again.

**Comment by Tazminia** [comment]
I moved the variable as requested.

**Review by juliocc — APPROVED** [review]

**Pull request merged**
